services:
  user-service:
    build: ./user-service
    ports:
      - "8016:8016"
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1

  forum-service:
    build: ./forum-service
    ports:
      - "9016:9016"
    network_mode: "host"
    environment:
      - PYTHONUNBUFFERED=1
